version: "3"

services:
    nginx_rp:
        build: nginx_rp
        image: img_revproxy2_rp
        container_name: revproxy2_rp
        volumes:
            - vol_letsencrypt:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - nginx_web1
            - nginx_web2
        restart: always

    nginx_web1:
        build: nginx_web1
        image: img_revproxy2_web1
        container_name: revproxy2_web1
        restart: always

    nginx_web2:
        build: nginx_web2
        image: img_revproxy2_web2
        container_name: revproxy2_web2
        restart: always

volumes:
    vol_letsencrypt:
        external: true
